### ISSUE TITLE
Completion does not work for sub-commands

### ISSUE THREAD

**Issue by jbraga** [oclif/plugin-autocomplete#9]
The plugin seems not to handle commands like "config:get" or "config:edit". 
It doesn't complete anything after the colon neither subcommand nor flags or arguments.

**Comment by ArchangelX360** [comment]
Same here, to add more context, it seems not to work for any of my machines running Unix (Linux or MacOS) with Bash version >= 4.

*DOES NOT WORK ON:*
$ echo $BASH_VERSINFO
4
$ echo $COMP_WORDBREAKS
"'><=;|&(:

*WORK ON:*
$ echo $BASH_VERSINFO
3
$ echo $COMP_WORDBREAKS
"'@><=;|&(:

@RasPhilCo I see you have a if block for that, do you know what the problem is?

**Comment by dlecan** [comment]
Anything that can be done to help here?

**Comment by RasPhilCo** [comment]
This plugin needs Bash 4 spiking and testing if you have time.

**Comment by dlecan** [comment]
hi @RasPhilCo, I'm testing [unik-name/uns-cli](/unik-name/uns-cli) build with Ocliff, plugin-autocomplete v0.1.5 and bash 4.4.20 on Linux.

```shell
$ uns <TAB><TAB>
autocomplete           cryptoaccount:create   help                   properties:list        send                   unik:create            unik:is-disclosed      version
cryptoaccount:address  cryptoaccount:read     properties:get         resolve                status                 unik:disclose          unik:read
```

```shell
$ uns unik:<TAB><TAB>

=> irrelevant: list local files
```
